name = "mfng"
main = "../../../dist/main-worker.js"
compatibility_date = "2023-02-21"

[dev]
port = 3000

[build]
command = "npm run build:main"
watch_dir = ["../..", "../../../node_modules"]

[assets]
bucket = "../../../dist/client"
serve_single_page_app = true

[[services]]
binding = "RSC"
service = "mfng-rsc"
